defaults:
  - config_schema
  - model: fno
  - training: default
  - _self_

dataset:
  name: turbulent_radiative_layer_2D
  n_steps_input: 4
  n_steps_output: 1
  batch_size: 4
  n_channels: 1

device: cuda
output_path: ${dataset.name}_fno_physicsnemo
